# Generated by Django 5.2.8 on 2025-11-24 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('class_name', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField()),
                ('location', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
